version: '3.8'

networks:
  app-network:
    driver: bridge

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: KSF_development
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3000:3000
      - 5555:5555
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}

    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres
    container_name: KSF_container
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:
